Update tomcat7.init
根据centos tomcat6 改动

diff --git a/tomcat7.init b/tomcat7.init
--- a/tomcat7.init
+++ b/tomcat7.init
@@ -1,153 +1,295 @@
 #!/bin/bash
-# Tomcat7 init script.
 #
-# chkconfig:  - 80 20
-# description:  Start/stop script for Tomcat6
+# tomcat7      This shell script takes care of starting and stopping Tomcat
+#
+# chkconfig: - 80 20
+#
+### BEGIN INIT INFO
+# Provides: tomcat7
+# Required-Start: $network $syslog
+# Required-Stop: $network $syslog
+# Default-Start:
+# Default-Stop:
+# Short-Description: start and stop tomcat
+### END INIT INFO
+#
 
-# Source function library.
-. /etc/rc.d/init.d/functions
-
-[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network
-[ "${NETWORKING}" = "no" ] && exit 0
-
-prog="tomcat7"
-[ -f /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
-
-TOMCATDEBUG=
-TOMCATSECURITY=${SECURITY:+"-security"}
-CATALINA_HOME=${CATALINA_HOME:="/opt/tomcat6"}
-RUNAS_USER=${RUNAS_USER:="tomcat"}
-WAITFOR=${WAITFOR:=3}
-CATALINA_PID="/var/run/${prog}.pid"
-RUN_SCRIPT="${CATALINA_HOME}/bin/catalina.sh"
-
-CDIR=$(pwd)
-
-JUNK=${JAVA_HOME:?"MUST BE CONFIGURED IN /etc/sysconfig/$prog"}
-if [ ! -d $JAVA_HOME ]; then
-  echo "$JAVA_HOME doesn't exist!"
-  exit 1
+## Source function library.
+#. /etc/rc.d/init.d/functions
+# Source LSB function library.
+if [ -r /lib/lsb/init-functions ]; then
+    . /lib/lsb/init-functions
+else
+    exit 1
 fi
 
-if [ ! -d $CATALINA_HOME ]; then
-  echo CATALINA_HOME does not exist as a valid directory: $CATALINA_HOME
-  exit 1
+DISTRIB_ID=`lsb_release -i -s 2>/dev/null`
+
+#NAME="$(basename $0)"
+NAME=`basename $0`
+echo "NAME=" $NAME
+unset ISBOOT
+if [ "${NAME:0:1}" = "S" -o "${NAME:0:1}" = "K" ]; then
+    NAME="${NAME:3}"
+    ISBOOT="1"
 fi
 
-export CATALINA_HOME CATALINA_PID JAVA_HOME
+# For SELinux we need to use 'runuser' not 'su'
+if [ -x "/sbin/runuser" ]; then
+    SU="/sbin/runuser -s /bin/sh"
+else
+    SU="/bin/su -s /bin/sh"
+fi
 
-cleanup() {
-  rm -f ${CATALINA_PID}
-}
+# Get the tomcat config (use this for environment specific settings)
+TOMCAT_CFG="/etc/tomcat7/tomcat7.conf"
+if [ -r "$TOMCAT_CFG" ]; then
+echo 'setup cfg by TOMCAT_CFG'    
+. $TOMCAT_CFG
+fi
 
-echoFailure() {
-  echo_failure
-  echo
-}
+# Get instance specific config file
+if [ -r "/etc/sysconfig/${NAME}" ]; then
+    . /etc/sysconfig/${NAME}
+fi
 
-echoSuccess() {
-  echo_success
-  echo
-}
+# Define which connector port to use
+CONNECTOR_PORT="${CONNECTOR_PORT:-8080}"
 
-start() {
-  echo -n "Starting $prog..."
-  STATUS=$(status >/dev/null)
-  R=$?
-  if [ $R -eq 0 ]; then
-    echo -n "$prog is already running. exiting."
-    echoFailure
-    return 1
-  fi
+# Path to the tomcat launch script
+TOMCAT_SCRIPT="/usr/sbin/tomcat7"
 
-  touch ${CATALINA_PID}
-  chown ${RUNAS_USER}:${RUNAS_USER} ${CATALINA_PID}
-  cd ${CATALINA_HOME}
-  runuser -s /bin/bash ${RUNAS_USER} -c "${RUN_SCRIPT} start >>${CATALINA_HOME}/logs/catalina.out 2>&1"
-  RETVAL=$?
-  cd ${CDIR}
-  if [ $RETVAL -eq 0 ]; then
-    echoSuccess
-  else
-    echoFailure
-  fi
-}
+# Tomcat program name
+TOMCAT_PROG="${NAME}"
+        
+# Define the tomcat username
+TOMCAT_USER="${TOMCAT_USER:-tomcat}"
 
-status() {
-  RETVAL=1
-  if [ -s ${CATALINA_PID} ]; then
-    read kpid < ${CATALINA_PID}
-    if checkpid $kpid 2>&1; then
-      echo "$prog is running ($kpid)"
-      RETVAL=0
-    else
-      echo "The lock file was found but no process running for pid $kpid."
+# Define the tomcat group
+TOMCAT_GROUP="${TOMCAT_GROUP:-`id -gn $TOMCAT_USER`}"
+
+# Define the tomcat log file
+TOMCAT_LOG="${TOMCAT_LOG:-/var/log/${NAME}-initd.log}"
+
+# Define the pid file name
+# If change is needed, use sysconfig instead of here
+export CATALINA_PID="${CATALINA_PID:-/var/run/${NAME}.pid}"
+
+RETVAL="0"
+
+function parseOptions() {
+    options=""
+    options="$options $(
+                 awk '!/^#/ && !/^$/ { ORS=" "; print "export ", $0, ";" }' \
+                 $TOMCAT_CFG
+             )"
+    if [ -r "/etc/sysconfig/${NAME}" ]; then
+        options="$options $(
+                     awk '!/^#/ && !/^$/ { ORS=" "; 
+                                           print "export ", $0, ";" }' \
+                     /etc/sysconfig/${NAME}
+                 )"
     fi
-  else
-    CHECKPROC="Dcatalina.home=${CATALINA_HOME}.*org.apache.catalina.startup.Bootstrap"
-    pid="$(pgrep -u ${RUNAS_USER} -f ${CHECKPROC})"
-      if [ -n "$pid" ]; then
-        echo "$prog is running ($pid) but no PID file exists (or it's empty)."
+    TOMCAT_SCRIPT="$options ${TOMCAT_SCRIPT}"
+    echo "TOMCAT_SCRIPT=" $TOMCAT_SCRIPT
+}
+
+# rhbz 757632
+function version() {
+	parseOptions
+	$SU - $TOMCAT_USER -c "${TOMCAT_SCRIPT} version" >> ${TOMCAT_LOG} 2>&1 || RETVAL="4"
+}
+
+# See how we were called.
+function start() {
+  
+   echo -n "Starting ${TOMCAT_PROG}: "
+   if [ "$RETVAL" != "0" ]; then 
+     log_failure_msg
+     return
+   fi
+   if [ -f "/var/lock/subsys/${NAME}" ]; then
+        if [ -f "${CATALINA_PID}" ]; then
+            read kpid < ${CATALINA_PID}
+#           if checkpid $kpid 2>&1; then
+            if [ -d "/proc/${kpid}" ]; then
+                log_success_msg
+                if [ "$DISTRIB_ID" = "MandrivaLinux" ]; then
+                    echo
+                fi
+                RETVAL="0"
+                return
+            fi
+        fi
+    fi
+    # fix permissions on the log and pid files
+    touch $CATALINA_PID 2>&1 || RETVAL="4"
+    if [ "$RETVAL" -eq "0" -a "$?" -eq "0" ]; then 
+      chown ${TOMCAT_USER}:${TOMCAT_GROUP} $CATALINA_PID
+    fi
+    if [ "$?" != "0" ]; then
+	RETVAL="4"
+    fi
+    parseOptions
+    if [ "$RETVAL" -eq "0" -a "$SECURITY_MANAGER" = "true" ]; then
+        $SU - $TOMCAT_USER -c "${TOMCAT_SCRIPT} start-security" \
+            >> ${TOMCAT_LOG} 2>&1 || RETVAL="4"
+    else
+       
+       [ "$RETVAL" -eq "0" ] && $SU - $TOMCAT_USER -c "${TOMCAT_SCRIPT} start" >> ${TOMCAT_LOG} 2>&1 || RETVAL="4"
+    fi
+    if [ "$RETVAL" -eq "0" ]; then 
+        log_success_msg
+        touch /var/lock/subsys/${NAME}
+    else
+        log_failure_msg "Error code ${RETVAL}"
+    fi
+    if [ "$DISTRIB_ID" = "MandrivaLinux" ]; then
+        echo
+    fi
+}
+
+function stop() {
+    echo -n "Stopping ${TOMCAT_PROG}: "
+    if [ -f "/var/lock/subsys/${NAME}" ]; then
+      parseOptions
+      if [ "$RETVAL" -eq "0" ]; then
+         touch /var/lock/subsys/${NAME} 2>&1 || RETVAL="4"
+         [ "$RETVAL" -eq "0" ] && $SU - $TOMCAT_USER -c "${TOMCAT_SCRIPT} stop" >> ${TOMCAT_LOG} 2>&1 || RETVAL="4"
+      fi
+      if [ "$RETVAL" -eq "0" ]; then
+         count="0"
+         if [ -f "${CATALINA_PID}" ]; then
+            read kpid < ${CATALINA_PID}
+            until [ "$(ps --pid $kpid | grep -c $kpid)" -eq "0" ] || \
+                      [ "$count" -gt "$SHUTDOWN_WAIT" ]; do
+                    if [ "$SHUTDOWN_VERBOSE" = "true" ]; then
+                        echo "waiting for processes $kpid to exit"
+                    fi
+                    sleep 1
+                    let count="${count}+1"
+                done
+                if [ "$count" -gt "$SHUTDOWN_WAIT" ]; then
+                    if [ "$SHUTDOWN_VERBOSE" = "true" ]; then
+                        log_warning_msg "killing processes which did not stop after ${SHUTDOWN_WAIT} seconds"
+                    fi
+                    kill -9 $kpid
+                fi
+                log_success_msg
+            fi
+            rm -f /var/lock/subsys/${NAME} ${CATALINA_PID}
+        else
+            log_failure_msg
+            RETVAL="4"
+        fi
+    else
+        log_success_msg
         RETVAL="0"
-      else
-        echo "$prog is stopped."
-      fi
     fi
-    return $RETVAL
+    if [ "$DISTRIB_ID" = "MandrivaLinux" ]; then
+        echo
+    fi
 }
 
-stop() {
-  echo -n "Stopping $prog."
-
-  if status >/dev/null; then
-    runuser -s /bin/bash ${RUNAS_USER} -c "${RUN_SCRIPT} stop >>${CATALINA_HOME}/logs/catalina.out 2>&1"
-
-    COUNT=0
-    while [ $COUNT -lt ${WAITFOR} ]; do
-      if status >/dev/null; then
-        echo -n "."
-        sleep 1
+function status()
+{
+   checkpidfile 
+   if [ "$RETVAL" -eq "0" ]; then
+      log_success_msg "${NAME} (pid ${kpid}) is running..."
+   elif [ "$RETVAL" -eq "1" ]; then
+      log_failure_msg "PID file exists, but process is not running"
+   else 
+      checklockfile
+      if [ "$RETVAL" -eq "2" ]; then
+         log_failure_msg "${NAME} lockfile exists but process is not running"
       else
-        echoSuccess
-        cleanup
-        return
+         pid="$(/usr/bin/pgrep -d , -u ${TOMCAT_USER} -G ${TOMCAT_GROUP} java)"
+         if [ -z "$pid" ]; then
+             log_success_msg "${NAME} is stopped"
+             RETVAL="3"
+         else
+             log_success_msg "${NAME} (pid ${kpid}) is running..."
+             RETVAL="0"
+         fi
       fi
-      COUNT=$(expr  $COUNT + 1)
-    done
-
-    echo
-    echo -n "$prog didn't stop, killing it softly.."
-    CHECKPROC="Dcatalina.home=${CATALINA_HOME}.*org.apache.catalina.startup.Bootstrap"
-    pid="$(pgrep -u ${RUNAS_USER} -f ${CHECKPROC})"
-    kill $pid
-    sleep 4
-    if status >/dev/null; then
-      echo
-      echo "Shutdown is taking too long, force stopping $prog."
-      kill -9 $pid
-      if status >/dev/null; then
-        echoFailure
-      else
-        echoSuccess
-        cleanup
-        return
-      fi
-    else
-      echoSuccess
-      cleanup
-      return
-    fi
-  else
-    echo
-    echo -n "$prog is not running. Exiting."
-    echoFailure
   fi
 }
 
+function checklockfile()
+{
+   if [ -f /var/lock/subsys/${NAME} ]; then
+      pid="$(/usr/bin/pgrep -d , -u ${TOMCAT_USER} -G ${TOMCAT_GROUP} java)"
+# The lockfile exists but the process is not running
+      if [ -z "$pid" ]; then
+         RETVAL="2"
+      fi
+   fi
+}
+
+function checkpidfile()
+{
+   if [ -f "${CATALINA_PID}" ]; then
+      read kpid < ${CATALINA_PID}
+      if [ -d "/proc/${kpid}" ]; then
+# The pid file exists and the process is running
+          RETVAL="0"
+         return
+      else
+# The pid file exists but the process is not running
+         RETVAL="1"
+         return
+      fi
+   else
+# pid file does not exist and program is not running
+      RETVAL="3"
+      return
+  fi
+}
+
+function usage()
+{
+   echo "Usage: $0 {start|stop|restart|condrestart|try-restart|reload|force-reload|status|version}"
+   RETVAL="2"
+}
+
+# See how we were called.
+RETVAL="0"
 case "$1" in
-  start)  start;;
-  stop)   stop;;
-  status) status;;
-  restart) stop ; start;;
-  *) echo "Usage: $0 [ start | stop | status | restart ]";;
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        start
+        ;;
+    condrestart|try-restart)
+        if [ -f "/var/run/${NAME}.pid" ]; then
+            stop
+            start
+        fi
+        ;;
+    reload)
+        RETVAL="3"
+        ;;
+    force-reload)
+        if [ -f "/var/run/${NAME}.pid" ]; then
+            stop
+            start
+        fi
+        ;;
+    status)
+        status
+        ;;
+    version)
+	 	version
+#        ${TOMCAT_SCRIPT} version
+        ;;
+    *)
+      usage
+      ;;
 esac
+
+exit $RETVAL
